# Generated by Django 5.0.2 on 2024-04-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=265, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
